name: C++ Build and Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install g++
      run: sudo apt-get install -y g++

    - name: Create build directory
      run: mkdir build

    - name: Compile and Run
      run: |
        cd "source code"
        for file in *.cpp; do
          filename=$(basename "$file" .cpp)
          g++ -o "../build/$filename" "$file"
          "../build/$filename"
        done
